[package]
name = "fastly-template-rust-default"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "^0.5.0"
log-fastly = "0.1.3"
log = "0.4.11"
config = "0.10.1"
